worker_processes 5;

events {
    worker_connections  1024;
}

http {
    include           mime.types;
    default_type      application/octet-stream;
    sendfile          on;
    keepalive_timeout 65;

    server {
        listen       80;
        server_name  $CONTENT_HOST;

        client_body_in_file_only clean;
        client_body_buffer_size 32K;

        client_max_body_size 300M;

        sendfile on;

        send_timeout           300;
        proxy_connect_timeout  300;
        proxy_send_timeout     300;
        proxy_read_timeout     300;

        location / {
            include proxy_headers.conf;
            proxy_pass   http://players:3000;
        }

        location ~ /.well-known/acme-challenge {
            allow   all;
            root    /usr/share/nginx/html;
        }

        location /content {
            include proxy_headers.conf;

            proxy_cache_key "$scheme$proxy_host$request_uri $http_range";
            proxy_set_header Range $http_range;

            proxy_pass   http://content:3000/content;
        }
    }
}
