services:
  #CouchDB instance to act as the discovery service API
  #
  couchdb:
    image: docker.io/bitnami/couchdb:3-debian-10
    environment:
      - COUCHDB_USER=${COUCHDBUSER}
      - COUCHDB_PASSWORD=${COUCHDBPASSWORD}
    ports:
      - '5984:5984'
      - '4369:4369'
      - '9100:9100'
    networks:
      - public
    volumes:
      - couchdb_data:/bitnami/couchdb
    restart: always

  # Nginx instance controlling traffic to each service
  #
  nginx:
    image: adl-discovery-nginx
    container_name: docker_nginx
    ports:
      - "8083:80"
      - "8443:443"
    volumes:
      - ./nginx_logs:/var/log/nginx
      - ./certbot/etc:/usr/share/keys
    depends_on:
      - couchdb  # Changed from adl-discovery-couchdb-1
    networks:
      - public

  # Certbot for SSL automation
  #
  certbot:
    container_name: 'discovery_certbot'
    image: certbot/certbot
    volumes:
      - ./keys:/var/lib/letsencrypt
      - ./nginx/letsencrypt:/data/letsencrypt
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/log:/var/log/letsencrypt
    depends_on:
      - nginx
    networks:
      - public

#volumes for CouchDB
volumes:
  couchdb_data:
    driver: local

#Network for the nginx server
networks:
  public:
    driver: bridge
